name: Go
on: [push, workflow_dispatch]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.24.6
      uses: actions/setup-go@v5
      with:
        go-version: 1.24.6
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v6
      with:
        version: '~> v2'
        args: --snapshot --skip publish --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload assets
      uses: actions/upload-artifact@v4
      with:
        name: Windows x86 32-bit
        path: dist/packwiz_windows_386_sse2/

    - name: Upload assets
      uses: actions/upload-artifact@v4
      with:
        name: Windows x86 64-bit
        path: dist/packwiz_windows_amd64_v1/

    - name: Upload assets
      uses: actions/upload-artifact@v4
      with:
        name: Windows Arm 32-bit
        path: dist/packwiz_windows_arm_6/

    - name: Upload assets
      uses: actions/upload-artifact@v4
      with:
        name: Windows Arm 64-bit
        path: dist/packwiz_windows_arm64_v8.0/

    - name: Upload assets
      uses: actions/upload-artifact@v4
      with:
        name: Linux x86 32-bit
        path: dist/packwiz_linux_386_sse2/

    - name: Upload assets
      uses: actions/upload-artifact@v4
      with:
        name: Linux x86 64-bit
        path: dist/packwiz_linux_amd64_v1/

    - name: Upload assets
      uses: actions/upload-artifact@v4
      with:
        name: Linux Arm 32-bit
        path: dist/packwiz_linux_arm_6/

    - name: Upload assets
      uses: actions/upload-artifact@v4
      with:
        name: Linux Arm 64-bit
        path: dist/packwiz_linux_arm64_v8.0/

    - name: Upload assets
      uses: actions/upload-artifact@v4
      with:
        name: Linux PowerPC 64-bit
        path: dist/packwiz_linux_ppc64_power8/

    - name: Upload assets
      uses: actions/upload-artifact@v4
      with:
        name: Linux RISC-V 64-bit
        path: dist/packwiz_linux_riscv64_rva20u64/

    - name: Upload assets
      uses: actions/upload-artifact@v4
      with:
        name: MacOS x86 64-bit
        path: dist/packwiz_darwin_amd64_v1/

    - name: Upload assets
      uses: actions/upload-artifact@v4
      with:
        name: MacOS Arm 64-bit
        path: dist/packwiz_darwin_arm64_v8.0/
